var path = 'recursos/imagenes/';
var _images_= [ 	
	{id:'fondo_a',     url:'recursos/imagenes/fondo_a.png'},
	{id:'fondo_b',     url:'recursos/imagenes/fondo_b.png'},
	{id:'fondo_c',     url:'recursos/imagenes/fondo_c.png'},
	{id:'fondo_d',     url:'recursos/imagenes/fondo_d.png'},
	{id:'logogly',     url:'recursos/imagenes/GYL.png'},
	{id:'titulo',     url:'recursos/imagenes/titulo.png'},
	{id:'fondo_nube_1',     url:'recursos/imagenes/fondo_nube_1.png'},
	{id:'fondo_nube_2',     url:'recursos/imagenes/fondo_nube_2.png'},
	
	//{id:'barra-inferior',     url:'recursos/imagenes/barra-inferior.png'},
	{id:'modos',     url:'recursos/imagenes/modos-10.png'},
	{id:'fondo_iconos_comandos',     url:'recursos/imagenes/fondo_iconos_comandos.png'},
	{id:'iconos_comandos',     url:'recursos/imagenes/iconos_comandos.png'},
	{id:'iconos_socialesplus',     url:'recursos/imagenes/iconos_socialesplus.png'},
	{id:'fondotexto',     url:'recursos/imagenes/fondotexto-12.png'},
	{id:'zonasensiblefull',     url:'recursos/imagenes/zonasensiblefull.png'},
	{id:'fondo_ayuda',     url:'recursos/imagenes/fondo_instrucciones.png'},
	{id:'cohete',     url:'recursos/imagenes/cohete.png'},
	{id:'pg_info',     url:'recursos/imagenes/pg_info.png'},
	{id:'enunciado_nivel1',     url:'recursos/imagenes/enunciado_nivel1.png'},
	{id:'enunciado_nivel2',     url:'recursos/imagenes/enunciado_nivel2.png'},
	{id:'enunciado_nivel3',     url:'recursos/imagenes/enunciado_nivel3.png'},
	{id:'barra_logros',     url:'recursos/imagenes/barra_logros_b1.png'},
	{id:'colors',     url:'recursos/imagenes/colors.png'},
	{id:'tit_excelente',     url:'recursos/imagenes/tit_excelente.png'},
	{id:'fondo_tranvia',     url:'recursos/imagenes/fondo_tranvia.png'},
	{id:'tiempo',     url:'recursos/imagenes/tiempo.png'},
	{id:'tiempo_accion',     url:'recursos/imagenes/tiempo-accion.png'},
	{id:'dejar_juego',     url:'recursos/imagenes/dejar_juego.png'},
	{id:'sino',     url:'recursos/imagenes/sino.png'},
	{id:'marco-blanco',     url:'recursos/imagenes/marco-blanco.png'},
	{id:'barra_logros_FONDO',     url:'recursos/imagenes/barra_logros_FONDO.png'},
	{id:'en-pausa',     url:'recursos/imagenes/en-pausa.png'},
	
	// Contanido Estático:
    {id: 'bgScore', url: path + 'puntaje.png'},
    {id: 'playExit', url: path + 'jugar_salir.png'},
    {id: 'bgIntro',url: path + 'Pres_fondo_presentacion.png'},
    {id: 'bgStars', url: path + 'Pres_estrellas.png'},
    {id: 'earthIntro',url: path + 'Pres_planeta_tierra.png'}, 
    {id: 'barraLogros',url: path + 'barra_logros.png'}, 
	{id: 'texto_intro',url: path + 'texto_intro.png'}, 
    {id: 'clockBorder',url: path + 'reloj_A.png'}, 
	{id: 'relojanim',url: path + 'relojanim.png'},
    {id: 'logogly',url: path + 'GYL.png'}, 
    {id: 'modos',url: path + 'modos-10.png'}, 
    {id: 'fondo_iconos_comandos',url: path + 'fondo_iconos_comandos.png'}, 
    {id: 'iconos_comandos',url: path + 'iconos_comandos.png'}, 
    {id: 'iconos_socialesplus',url: path + 'iconos_socialesplus.png'}, 
    {id: 'fondotexto',url: path + 'fondotexto-12.png'}, 
    {id: 'zonasensiblefull',url: path + 'zonasensiblefull.png'}, 
    {id: 'fondo_ayuda',url: path + 'fondo_instrucciones.png'}, 
    {id: 'cohete',url: path + 'cohete.png'}, 
    {id: 'pg_info',url: path + 'pg_info.png'}, 
    {id: 'barra_logros',url: path + 'barra_logros_b.png'}, 
    {id: 'colors',url: path + 'colors.png'}, 
    {id: 'tit_excelente',url: path + 'tit_excelente.png'}, 
    {id: 'tit_intento1',url: path + 'tit_intento1.png'}, 
    {id: 'tit_intento2',url: path + 'tit_intento2.png'}, 
    {id: 'tit_intento3',url: path + 'tit_intento3.png'}, 
    {id: 'dejar_juego',url: path + 'dejar_juego.png'}, 
    {id: 'sino',url: path + 'sino.png'}, 
    {id: 'marco-blanco',url: path + 'marco-blanco.png'}, 
    {id: 'en-pausa',url: path + 'en-pausa.png'},
	{id: 'jugar_salir',url: path + 'jugar_salir.png'},
	{id: 'puntaje',url: path + 'puntaje.png'},
	{id: 'sprite-motor',url: path + 'sprite-motor.png'},
	{id: 'estrella',url: path + 'estrella.png'},
];


var _audio_= [
	{id:'COMENZAR',     					url:"recursos/sonidos/COMENZAR.mp3"					},
	{id:'CONTROLES',     					url:"recursos/sonidos/CONTROLES.mp3"				},
	{id:'ELEMENTO',    						url:"recursos/sonidos/ELEMENTO.mp3"					},
	{id:'ESTRELLA',     					url:"recursos/sonidos/ESTRELLA.mp3"					},
	{id:'EXCELENTE',     					url:"recursos/sonidos/EXCELENTE.mp3"				},
	{id:'FALLIDO',     						url:"recursos/sonidos/INTENTO_FALLIDO.mp3"			},
	{id:'PASAR-NIVEL',     					url:"recursos/sonidos/PASAR_NIVEL.mp3"				},
	{id:'SELECCION-RELAJADO-TIEMPO',     	url:"recursos/sonidos/SELECCION_RELAJADO_TIEMPO.mp3"},
	{id:'TITULO-ABRE',     					url:"recursos/sonidos/TITULO_ABRE.mp3"				},
	{id:'TIME_OVER',     					url:"recursos/sonidos/TIME_OVER.mp3"				},
	{id:'CORRECTO',     					url:"recursos/sonidos/CORRECTO.mp3"					},
	{id:"pasar_de_nivel" ,					url: "recursos/sonidos/pasar_de_nivel.mp3"},
	{id:"animo_1" , 						url: "recursos/sonidos/animo_1.mp3"},
	{id:"animo_2" , 						url: "recursos/sonidos/animo_2.mp3"},
	{id:"reloj" , 							url: "recursos/sonidos/reloj.mp3"},
	{id:"excelente_2" , 					url: "recursos/sonidos/excelente_2.mp3"},
	
	
];

subtmitfiles(_images_);
