var path = 'recursos/imagenes/';
var _images= [
	{id: 'bgIntro',url: path + 'Pres_fondo_presentacion.png'},
    {id: 'bgStars', url: path + 'Pres_estrellas.png'},
    {id: 'earthIntro',url: path + 'Pres_planeta_tierra.png'}, 
    {id: 'barraLogros',url: path + 'barra_logros.png'}, 
    {id: 'clockBorder',url: path + 'reloj_A.png'}, 
	{id:'fondo_a',     url:'recursos/imagenes/fondo_a.png'},
	{id:'fondo_b',     url:'recursos/imagenes/fondo_b.png'},
	{id:'fondo_c',     url:'recursos/imagenes/fondo_c.png'},
	{id:'fondo_d',     url:'recursos/imagenes/fondo_d.png'},
	{id:'logogly',     url:'recursos/imagenes/GYL.png'},
	{id:'nube_titulo',     url:'recursos/imagenes/nube_titulo.png'},
	{id:'titulo',     url:'recursos/imagenes/titulo.png'},
	{id:'modos',     url:'recursos/imagenes/modos-10.png'},
	{id:'fondo_iconos_comandos',     url:'recursos/imagenes/fondo_iconos_comandos.png'},
	{id:'iconos_comandos',     url:'recursos/imagenes/iconos_comandos.png'},
	{id:'iconos_socialesplus',     url:'recursos/imagenes/iconos_socialesplus.png'},
	{id:'fondotexto',     url:'recursos/imagenes/fondotexto-12.png'},
	{id:'zonasensiblefull',     url:'recursos/imagenes/zonasensiblefull.png'},
	{id:'fondo_ayuda',     url:'recursos/imagenes/fondo_instrucciones.png'},
	{id:'cohete',     url:'recursos/imagenes/cohete.png'},
	{id:'pg_info',     url:'recursos/imagenes/pg_info.png'},
	{id:'enunciado_nivel1',     url:'recursos/imagenes/enunciado_nivel1.png'},
	{id:'enunciado_nivel2',     url:'recursos/imagenes/enunciado_nivel2.png'},
	{id:'enunciado_nivel3',     url:'recursos/imagenes/enunciado_nivel3.png'},
	{id:'barra_logros',     url:'recursos/imagenes/barra_logros_b.png'},
	{id:'colors',     url:'recursos/imagenes/colors.png'},
	{id:'tit_excelente',     url:'recursos/imagenes/tit_excelente.png'},
	{id:'tit_intento1',     url:'recursos/imagenes/tit_intento1.png'},
	{id:'tit_intento2',     url:'recursos/imagenes/tit_intento2.png'},
	{id:'tit_intento3',     url:'recursos/imagenes/tit_intento3.png'},
	{id:'fondo_tranvia',     url:'recursos/imagenes/fondo_tranvia.png'},
	{id:'dejar_juego',     url:'recursos/imagenes/dejar_juego.png'},
	{id:'sino',     url:'recursos/imagenes/sino.png'},
	{id:'marco-blanco',     url:'recursos/imagenes/marco-blanco.png'},
	{id:'en-pausa',     url:'recursos/imagenes/en-pausa.png'},
	{id:'grilla',     url:'recursos/imagenes/j1/grilla-14.png'},
	{id:'bggrilla',     url:'recursos/imagenes/j1/bggrilla-11.png'},
	{id:'bichos',     url:'recursos/imagenes/j1/escena1_insectos.png'},
	{id:'bichosGrandes',     url:'recursos/imagenes/j1/escena2_insectos.png'},
	{id:'enunciado',     url:'recursos/imagenes/j1/escena1/escena1_enunciado.png'},
	{id:'enunciado1',     url:'recursos/imagenes/j1/escena2/escena2_enunciado.png'},
	{id:'enunciado2',     url:'recursos/imagenes/j1/escena3/escena3_enunciado.png'},
	{id:'numeros',     url:'recursos/imagenes/j1/numeros.png'},
	{id:'letras',     url:'recursos/imagenes/j1/letras.png'},
	{id:'punto',     url:'recursos/imagenes/j1/punto.png'},
	{id:'figura1',     url:'recursos/imagenes/j1/escena3/esc_3_cuadrado_rosado.png'},
	{id:'figura2',     url:'recursos/imagenes/j1/escena3/esc_3_cuadrado_verde.png'},
	{id:'figura3',     url:'recursos/imagenes/j1/escena3/esc_3_rombo_morado.png'},
	{id:'figura4',     url:'recursos/imagenes/j1/escena3/esc_3_rombo_rojo.png'},
	{id:'figura5',     url:'recursos/imagenes/j1/escena3/esc_3_triangulo_azul.png'},
	{id:'figura6',     url:'recursos/imagenes/j1/escena3/esc_3_triangulo_naranjo.png'},
	{id:'fondodd',     url:'recursos/imagenes/j1/escena3/menu_desplegable_fondo.png'},
];
