var _images_= [ 	
	{id:'fondo_a',     url:'recursos/imagenes/fondo_a.png'},
	{id:'fondo_b',     url:'recursos/imagenes/fondo_b.png'},
	{id:'fondo_c',     url:'recursos/imagenes/fondo_c.png'},
	{id:'fondo_d',     url:'recursos/imagenes/fondo_d.png'},
	{id:'logogly',     url:'recursos/imagenes/GYL.png'},
	{id:'nube_titulo',     url:'recursos/imagenes/j3/intro_titulo.png'},
	{id:'titulo',     url:'recursos/imagenes/j3/intro_titulo.png'},
	{id:'modos',     url:'recursos/imagenes/modos-10.png'},
	{id:'fondo_iconos_comandos',     url:'recursos/imagenes/fondo_iconos_comandos.png'},
	{id:'iconos_comandos',     url:'recursos/imagenes/iconos_comandos.png'},
	{id:'iconos_socialesplus',     url:'recursos/imagenes/iconos_socialesplus.png'},
	{id:'fondotexto',     url:'recursos/imagenes/fondotexto-12.png'},
	{id:'zonasensiblefull',     url:'recursos/imagenes/zonasensiblefull.png'},
	{id:'fondo_ayuda',     url:'recursos/imagenes/fondo_instrucciones.png'},
	{id:'cohete',     url:'recursos/imagenes/cohete.png'},
	{id:'pg_info',     url:'recursos/imagenes/pg_info.png'},
	{id:'enunciado_nivel1',     url:'recursos/imagenes/enunciado_nivel1.png'},
	{id:'enunciado_nivel2',     url:'recursos/imagenes/enunciado_nivel2.png'},
	{id:'enunciado_nivel3',     url:'recursos/imagenes/enunciado_nivel3.png'},
	{id:'barra_logros',     url:'recursos/imagenes/barra_logros_b.png'},
	{id:'colors',     url:'recursos/imagenes/colors.png'},
	{id:'tit_excelente',     url:'recursos/imagenes/tit_excelente.png'},
	{id:'tit_intento1',     url:'recursos/imagenes/tit_intento1.png'},
	{id:'tit_intento2',     url:'recursos/imagenes/tit_intento2.png'},
	{id:'tit_intento3',     url:'recursos/imagenes/tit_intento3.png'},
	{id:'fondo_tranvia',     url:'recursos/imagenes/fondo_tranvia.png'},
	{id:'tiempo',     url:'recursos/imagenes/tiempo.png'},
	{id:'tiempo_accion',     url:'recursos/imagenes/tiempo-accion.png'},
	{id:'dejar_juego',     url:'recursos/imagenes/dejar_juego.png'},
	{id:'sino',     url:'recursos/imagenes/sino.png'},
	{id:'marco-blanco',     url:'recursos/imagenes/marco-blanco.png'},
	{id:'barra_logros_FONDO',     url:'recursos/imagenes/barra_logros_FONDO.png'},
	{id:'en-pausa',     url:'recursos/imagenes/en-pausa.png'},
	
	{id:'fondobosque',     url:'recursos/imagenes/j3/RA1_ECbosque.png'},
	{id:'fondoselva',     url:'recursos/imagenes/j3/RA2_ECamazonas.png'},
	{id:'fondosartocp',     url:'recursos/imagenes/j3/RA3_ECantartica.png'},
	{id:'fondopradera',     url:'recursos/imagenes/j3/RA4_ECpradera.png'},
	{id:'fondosmarino',     url:'recursos/imagenes/j3/RA5_ECmarino.png'},
	{id:'fondosabana',     url:'recursos/imagenes/j3/RA6_ECsabana.png'},
	{id:'enunciae1',     url:'recursos/imagenes/j3/N1_enunciado.png'},
	{id:'enunciae2',     url:'recursos/imagenes/j3/N2_enunciado.png'},
	{id:'enunciae3',     url:'recursos/imagenes/j3/N3_enunciado.png'},
	{id:'circulo',     url:'recursos/imagenes/j3/circulo-blanco.png'},
	{id:'conjunto-circulos',     url:'recursos/imagenes/j3/conjunto-circulos-blancos.png'},
	{id:'especies',     url:'recursos/imagenes/j3/ESPECIES.png'},
];
var _sonido_espe_ = [
	{id:"bgmusic" , url: "recursos/sonidos/j3/MUSICA-BIOLOGIA.ogg"},
	{id:"sonidoTitulo" , url: "recursos/sonidos/j2/VJ_001L_titulo.mp3"},
	{id:"sonidoIntro" , url: "recursos/sonidos/j2/VJ_001L_intro.mp3"},
	{id:"sonidoEnunciado" , url: "recursos/sonidos/j2/VJ_001L_enunciado.mp3"}
];
subtmitfiles(_images_);